version: "3"
services:
  database:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: handsome
      POSTGRES_DB: vendure
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

volumes:
  postgres_data: